-----------------------------------------------------------------------------
-- gutentags
-- @todo: remove as it has never been used...
-----------------------------------------------------------------------------
-- vim.g.gutentags_ctags_auto_set_tags = 0
-- vim.g.gutentags_file_list_command = "git ls-files"

-----------------------------------------------------------------------------
-- neoformat
-----------------------------------------------------------------------------

---- map('n', '<leader>p', ':Neoformat prettier<CR>', options)
---- use a project-local version of Prettier
--vim.g.neoformat_try_node_exe = 1
---- Enable alignment
--vim.g.neoformat_basic_format_align = 1
---- Enable tab to spaces conversion
--vim.g.neoformat_basic_format_retab = 1
---- Enable trimmming of trailing whitespace
--vim.g.neoformat_basic_format_trim = 1

----run Prettier on save
---- vim.cmd([[
----     autocmd BufWritePre *.js Neoformat
---- ]])

-----------------------------------------------------------------------------
-- ale (NOT USED)
-----------------------------------------------------------------------------
-- local l = {}
-- l.javascript = {'eslint', 'prettier'}
-- l.javascriptreact = {'eslint', 'prettier'}
-- l.typescript = {'eslint', 'prettier'}
-- l.typescriptreact = {'eslint', 'prettier'}
-- l.css = {'prettier'}
-- l.svelte = {'prettier'}

-- vim.g.ale_fixers = l
-- -- vim.g.ale_sign_error = '❌'
-- -- vim.g.ale_sign_warning = '⚠️'
-- vim.g.ale_fix_on_save = 1
-- local aliases = {}
-- aliases.jsx =  'javascript'
-- aliases.jsx =  'javascript'
-- vim.g.ale_linter_aliases = aliases


-----------------------------------------------------------------------------
--- aerial
-- @todo: Remove this as i never use it
-----------------------------------------------------------------------------
-- require('aerial').setup({
--     attach_mode = "global",
--     backends = {"treesitter", "lsp", "markdown" },
--     layout = {
--         min_width = 28,
--     }
--     ,
--     show_guides = true,
--     -- filter_kind = false,
--     guides = {
--         mid_item = "├ ",
--         last_item = "└ ",
--         nested_top = "│ ",
--         whitespace = "  ",
--     },
--     nerd_font = "auto",
--     manage_folds = true,
--     link_folds_to_tree = true,
--     link_tree_to_folds = true,
--     on_attach = function(bufnr)
--         -- Toggle the aerial window with <leader>a
--         vim.api.nvim_buf_set_keymap(bufnr, 'n', '<leader>a', '<cmd>AerialToggle!<CR>', {})
--         -- Jump forwards/backwards with '{' and '}'
--         -- vim.api.nvim_buf_set_keymap(bufnr, 'n', '(', '<cmd>AerialPrev<CR>', {})
--         -- vim.api.nvim_buf_set_keymap(bufnr, 'n', ')', '<cmd>AerialNext<CR>', {})
--         -- Jump up the tree with '[[' or ']]'
--         -- vim.api.nvim_buf_set_keymap(bufnr, 'n', '[[', '<cmd>AerialPrevUp<CR>', {})
--         -- vim.api.nvim_buf_set_keymap(bufnr, 'n', ']]', '<cmd>AerialNextUp<CR>', {})
--     end
-- })
